### ISSUE TITLE
Setup serveur rocketchat.drave.quebec

### ISSUE THREAD

**Issue by rngadam** [dravedev/devops#1]
https://docs.google.com/drawings/d/12i6-27wcS1MW3kGS3WfcBBJdPBcdhMNQjJV28kqC_Kw/edit

![Diagramme](https://docs.google.com/drawings/d/e/2PACX-1vRoX4QEXdmrv0ZRfSQf_ChHyII-63IWZV2UlJZ7z95PbbflhsPyH_hdt-_B4uuf6UB0NN8bTMcJNRFU/pub?w=1440&h=1080)

**Comment by rngadam** [comment]
la recommendation c'est d'utiliser des containers docker pour rocket.chat:

https://docs.rocket.chat/installation/official-recommendations

trouver rôle pour faire la liste de tâches équivalentes:

* https://docs.rocket.chat/installation/docker-containers

mettre dans le playbook.yml et utiliser les tags pour tester des tâches spécifiques.

Suggère de commencer par tester le setup docker et rocketchat et de tester avec ssh port forwarding avant de l'ouvrir à travers nginx.

**Comment by jvtrudel** [comment]
Ce sujet a été reporté à plus tard.
